### ISSUE TITLE
Provide a ${CLASS_NAME} parameter to the template

### ISSUE THREAD

**Issue by nikophil** [ruslan-polutsygan/phpstorm-adder-remover-generator-plugin#2]
Hello, and thanks for your plugin. 

Is there a way that you provide a ${CLASS_NAME} parameter to the template please ? 

For a bidirectionnal ManyToOne doctrine relation, i'm use to do such adder / remover : 

```
/** 
 * @param Role $role 
 * @return $this 
 */ 
public function addRole(Role $role) 
{
    if (!$this->roles->contains($role)) { 
        $this->roles->add($role); 
        $role->setUser($this); 
    }

    return $this; 
} 

/**
 * @param Role $role 
 * @return $this 
 */ 
public function removeRole(Role $role) 
{ 
    if (!$this->roles->contains($role)) {
        $this->roles->removeElement($role);
        $role->setUser(null); 
    } 

    return $this; 
} 
```

and there is no way to get the "setUser" method unless we have a ${CLASS_NAME} parameter. 

Thank you

**Comment by ruslan-polutsygan** [comment]
Hello @nikophil 

Not sure I got you mean.
Do you want this getter/setter part `$role->setUser($this); ` to be generated as well?
And the problem is that method name `setUser` cannot be templated for now. Correct?

What would you want `${CLASS_NAME}` var to be in above example? How would you use it in template?

**Comment by nikophil** [comment]
Hello @ruslan-polutsygan  

and thank for your answer.

the template for the adder should look like this :

```
/**
 * @param ${TYPE_HINTED_PARAM}
 * @return $this
 */
public function ${METHOD_NAME}(${TYPE_HINTED_PARAM})
{
#if (${IS_DOCTRINE_COLLECTION} == "doctrine")
    if (!$this->${FIELD_NAME}->contains(${PARAM_NAME})) {
        $this->${FIELD_NAME}->add(${PARAM_NAME});
        ${PARAM_NAME}->set${CLASS_NAME}($this);
    }
#else
    $this->${FIELD_NAME}[] = ${PARAM_NAME};
#end
    
    return $this;
}
```
Notice the **set${CLASS_NAME}$**

This would be very nice to generate clean adders and removers for Doctrine's OneToMany associations

**Comment by ruslan-polutsygan** [comment]
@nikophil done. 
Template variable called `${THIS_CLASS_NAME}`. Reset templates to defaults and you will see it there

**Comment by nikophil** [comment]
Thank you very much :)
