### ISSUE TITLE
Use imported class name for vdoc

### ISSUE THREAD

**Issue by Koc** [ruslan-polutsygan/phpstorm-adder-remover-generator-plugin#3]
from example

``` php
namespace App\Entity;

class Entity
{
    /**
     * @var User[]
     */
    protected $users;

    /**
     * @param \App\Entity\User $user
     */
    public function addUser(User $user)
    {
        $this->users[] = $user;
    }
}
```

User is imported already, so it better use short class name `* @param User $user` instead of `* @param \App\Entity\User $user`

**Comment by ruslan-polutsygan** [comment]
Hi @Koc 

Yes, agree.

**Comment by ruslan-polutsygan** [comment]
`${TYPE_HINT}` var reset to just class name.
`${TYPE_HINT_FQCN}` template added to return FQCN(old behavior of `${TYPE_HINT}`). For those whole like to see fqcn in phpdocs(I'm among them).
