### ISSUE TITLE
Inject code to cursor position

### ISSUE THREAD

**Issue by Bonemeijer** [ruslan-polutsygan/phpstorm-adder-remover-generator-plugin#6]
As a developer, I would like generated code to be injected at the cursor so it matches the default editor's behaviour.

When I put my cursor halfway a class and then choose "Generate Adders", the generated code is injected at the end of the class.

Instead, I would expect the code to be injected at the first possible opportunity. For example; when using the default PhpStorms "Generate Getters" functionality, it adds the generated code at the cursor, or after the current method when the cursor is in a method.

**Comment by ruslan-polutsygan** [comment]
Done in 0.3.4. New version is published.
