### ISSUE TITLE
Recognize concrete Doctrine Collection implementations

### ISSUE THREAD

**Issue by Bonemeijer** [ruslan-polutsygan/phpstorm-adder-remover-generator-plugin#7]
As a developer, I would like the generator to detect concrete Doctrine collections, so I can typehint my protected properties on a concrete instead of an interface.

Right now, I *have* to typehint on `Doctrine\Common\Collections\Collection` or `Collection` and import. 

This plugin would be even better if it would check typehint inheritance so concrete implementations of the Collection interface would also correctly be detected as a "doctrine property".

For example, typehinting on `Doctrine\Common\Collections\ArrayCollection` and then choosing "Generate Adders" results in a default adder instead of the doctrine-specific one.

**Comment by ruslan-polutsygan** [comment]
Done in 0.3.4. New version is published.

**Comment by Bonemeijer** [comment]
Cheers for picking this up. I just updated but it doesn't work for me yet.
Are there any special instructions I should be following?

Typehinting on `Collection` does still work, though.

**Comment by ruslan-polutsygan** [comment]
Hi
You don't need to anything special. Just update the plugin and restart your IDE.
Just checked myself. I added property `$users`, typehinted it with doctrine `ArrayCollection` and generated accessors.  Here is what I got generated -  - https://i.imgur.com/XDedRPc.png
My PhpStorm version is 2017.1.

**Comment by Bonemeijer** [comment]
Thanks for your quick reply. Your example works fine for me as well. 
However, when I typehint only on `ArrayCollection` without the added `object array` typehint, it breaks for me. Please try the code below:

`<?php

namespace Sample;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Security\Core\User\User;

/**
 * Class SampleObject
 */
class SampleObject
{
    /** @var array */
    protected $array = [];
    
    /** @var Collection */
    protected $collection;
    
    /** @var ArrayCollection */
    protected $arrayCollection;

    /** @var ArrayCollection|User[] */
    protected $arrayCollectionWithArray;
}
`

I use PHPStorm 2017.1 also and the latest version of your plugin. 
![screen shot 2017-03-28 at 09 37 17](https://cloud.githubusercontent.com/assets/7499085/24393884/30cb685a-139a-11e7-97e9-8b5ee02271f3.png)

**Comment by ruslan-polutsygan** [comment]
Created an issue for this https://github.com/ruslan-polutsygan/phpstorm-adder-remover-generator-plugin/issues/8
Thanks for reporting.
