### ISSUE TITLE
Field typehinted with just `ArrayCollection` is not recognized

### ISSUE THREAD

**Issue by ruslan-polutsygan** [ruslan-polutsygan/phpstorm-adder-remover-generator-plugin#8]
https://github.com/ruslan-polutsygan/phpstorm-adder-remover-generator-plugin/issues/7#issuecomment-289688582

**Comment by ruslan-polutsygan** [comment]
Hi @Bonemeijer
Must be working now. Check 0.3.5 version please.

**Comment by Bonemeijer** [comment]
Works fine! Cheers for fixing!
