### ISSUE TITLE
Update remover template for plain arrays

### ISSUE THREAD

**Issue by Koc** [ruslan-polutsygan/phpstorm-adder-remover-generator-plugin#9]
There is an error in operators priorities https://github.com/kalessil/phpinspectionsea/issues/442#issuecomment-320047539

**Comment by ruslan-polutsygan** [comment]
Hi
If I understood you correctly, you want parentheses around `$x = array_search(...)` ?
You can do it in template settings - https://i.imgur.com/XWmIYA2.png. Generated remover would be https://i.imgur.com/euR7Kob.png.

**Comment by Koc** [comment]
Yes, I've edited templates some time ago. But issue about default templates which shipped with plugin.

**Comment by ruslan-polutsygan** [comment]
OK. Will make update when I have time.
Thanks for reporting.

**Comment by mikvet** [comment]
Hello everyone, 
I found the same bug a few hours ago. In the meantime, thank you for the template fix :-) it works for me.

Any plans in accepting this PR ? It will save some future developers a few gray hairs ;-) in the current state, the second element of the array is always removed and you may not notice it while debugging.

thank you for this great plugin, have fun!

**Comment by ruslan-polutsygan** [comment]
@Koc @mikvet 
Wow! Haven't realized that three months have been since issue opened and PR sent! 
Will merge this week. Sorry.

**Comment by ruslan-polutsygan** [comment]
PR merged, new version released. Please check
